version: '3.8'
services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-price_bot_db}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5430:5432"
    networks:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres:
    driver: local

networks:
  postgres:
    driver: bridge