"""add price 

Revision ID: 3d310f20d519
Revises: 2f79174ecc36
Create Date: 2025-04-17 08:51:57.033491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d310f20d519'
down_revision: Union[str, None] = '2f79174ecc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawling_target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawling_target', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
